# Replace with valid credentials
consumer_token = '************'
consumer_secret = '************'
access_token = '************'
access_secret = '************'

# LOCATION:
#   Specify a state name (e.g. state = "New York"), and pyglit will filter using an bbox automatically generated for
#   the state specified using the coordinates from http://mbostock.github.io/protovis/ex/us_lowres.js. As long as
#   a state name is specified, pyglit ignores the bbox variable below.
state = "New York"

#   If you want to use a custom bounding box instead of one automatically generated by pyglit, supply the
#   coordinates for the bbox variable below and set the state variable above to be None.
bbox = [-92.964215,42.457983,-86.708830,47.083097] # (min_long, min_lat, max_long, max_lat)

# max number of tweets to collect
tweet_limit = 100000